import "..\\mac\\extra\\RUnit\\RUnit.Mac";
import "..\\mac\\extra\\OOP\\Comparators.Mac";
//RUnitTest.SHOW_SUCCEED_FUN = true;

Private Class Account(_acc : String, _summ : Integer)
   var acc = _acc;
   var summ = _summ;

   Macro compareTo(othAcc : Account)
      if(acc > othAcc.acc)
         return 1;
      elif(acc < othAcc.acc)
         return -1;
      else
       if(summ > othAcc.summ)
            return 1;
         elif (summ > othAcc.summ)
            return -1;
          else
             return 0;
         end;
      end;
   End;
End;


Private Class AccountPriv(_acc : String, _summ : Integer)
   private var acc = _acc;
   private var summ = _summ;
End;

Class (TestCase) TestObjectComparator()
   var comp;
   var func;

   Macro co(a, b)
      return (ExecMacro2(func, a, b));
   end;

   Macro test_objComp()
      var a, b, c;
      a = Account("4081700", 100);
      b = Account("4081701", 200);
      c = Account("4081701", 100);
      AssertEquals(-1, a.compareTo(b));
      AssertEquals(1, b.compareTo(a));
      AssertEquals(1, b.compareTo(c));
      AssertEquals(1, c.compareTo(a));

      comp = CF_ObjectComparator("summ", "acc");
      func = comp.getFunc();
      AssertEquals(-1, co(a, b));
      AssertEquals(1, co(b, c));
      AssertEquals(-1, co(a, c));

      comp = CF_ObjectComparator("-summ", "acc");
      func = comp.getFunc();
      AssertEquals(1, co(a, b));
      AssertEquals(-1, co(b, c));
      AssertEquals(-1, co(a, c));
      comp = CF_ObjectComparator("-summ", "-acc");
      func = comp.getFunc();
      AssertEquals(1, co(a, b));
      AssertEquals(-1, co(b, c));
      AssertEquals(1, co(a, c));
   End;

   Macro test_objComp2()
      var a, b, c;
      a = AccountPriv("4081700", 100);
      b = AccountPriv("4081701", 200);
      c = AccountPriv("4081701", 100);

      comp = CF_ObjectComparator2(AccountPriv,"summ", "acc");
      func = comp.getFunc();
      AssertEquals(-1, co(a, b));
      AssertEquals(1, co(b, c));
      AssertEquals(-1, co(a, c));

      comp = CF_ObjectComparator2(AccountPriv, "-summ", "acc");
      func = comp.getFunc();
      AssertEquals(1, co(a, b));
      AssertEquals(-1, co(b, c));
      AssertEquals(-1, co(a, c));
      comp = CF_ObjectComparator2(AccountPriv, "-summ", "-acc");
      func = comp.getFunc();
      AssertEquals(1, co(a, b));
      AssertEquals(-1, co(b, c));
      AssertEquals(1, co(a, c));
   End;


End;

TestObjectComparator();
