import "..\\mac\\extra\\RUnit\\RUnit.Mac";
import "..\\mac\\extra\\Tests\\Utils\\UT_SArray.mac";
import "..\\mac\\extra\\Tests\\Utils\\UT_StringUtils.mac";
import "..\\mac\\extra\\Tests\\Collections\\UT_Lists.mac";
import "..\\mac\\extra\\Tests\\Collections\\UT_Maps.mac";
import "..\\mac\\extra\\Tests\\Collections\\UT_Sets.mac";
import "..\\mac\\extra\\Tests\\Lambda\\UT_Lambda.mac";
import "..\\mac\\extra\\Tests\\OOP\\UT_OOP.mac";
import "..\\mac\\extra\\Tests\\OOP\\UT_Comparators.mac";
import "..\\mac\\extra\\Tests\\StreamApi\\UT_Stream.mac";


RUnitTest.SHOW_SUCCEED_FUN = false;