import "../mac/extra/RUnit/RUnit.Mac";
import "../mac/extra/utils/SArray.mac";
import bankinter;
RUnitTest.SHOW_ONLY_FAILED_UNIT_FUN = false;

// Тестовый класс для объектных коллекций
Private Class Account(_acc : String, _summ : Integer)
   var acc = _acc;
   var summ = _summ;

   Macro compareTo(othAcc : Account)
      if(acc > othAcc.acc)
         return 1;
      elif(acc < othAcc.acc)
         return -1;
      else
         if(summ > othAcc.summ)
            return 1;
         elif (summ > othAcc.summ)
            return -1;
         else
            return 0;
         end;
      end;
   End;

   Macro toString() : String
      return acc + " - " + summ;
   End;
End;

Macro compareJustAcc(acc1, acc2)
   if(acc1.acc == acc2.acc)
      return 0;
   elif(acc1.acc < acc2.acc)
      return -1;
   else
      return 1;
   end;
End;

Macro otherCompFun(a1,a2)
   return CF_ComparePrimitive(a1.acc,a2.acc);
end;

Macro otherCompFun2(a1,a2)
   return CF_ComparePrimitive(a1.summ, a2.summ);
end;

Macro equalAbs(i1, i2)
   return (abs(i1) == abs(i2));
End;

Private Macro filterFunc(el) : Bool
   return (GenCLassName(el) == "INTEGER");
end;

Private Macro mapFunc(el) : Integer
   return (el*el);
End;

private Macro reduceFunc(acc, el)
   return acc + el;
End;


Class (UnitTest) TestSArray()
   var arr;

   Macro beforeTest()
      arr = SArray();
   End;

   Macro fullfillArr()
      arr = SArray("first", 2, null, Account("4081700000000123", 100), 3, 12, Account("4081700000000666", 505), null, 2);
   End;

   Macro test_add()
      assertEquals(0, arr.size);
      arr.add(1);
      assertEquals(1, arr.size);
      arr.add(2, 0);
      assertEquals(2, arr[0]);
      assertEquals(1, arr[1]);
      assertEquals(2, arr.size);
      arr.add(18, 1);
      assertEquals(3, arr.size);
      assertArrays(arr_(2, 18, 1), arr);
   End;

   Macro test_get()
      arr = SArray(1, 2, 3);
      assertEquals(2, arr.get(1));
      //assertError(arr.get(-1));
   End;

   Macro test_push()
      arr.push("one");
      assertArrays(arr_("one"), arr);
      arr.push("two");
      assertArrays(arr_("one", "two"), arr);
   End;

   Macro test_peek()
      assertNull(arr.peek);
      arr.addAll(1,2,3);
      assertEquals(3, arr.peek);
      assertEquals(3, arr.size);
   End;

   Macro test_pop()
      arr.addAll(1, 2, 3);
      assertEquals(3, arr.pop);
      assertEquals(2, arr.pop);
      assertEquals(1, arr.pop);
      assertEquals(0, arr.size);
   End;

   Macro test_poll()
      assertNull(arr.poll);
      arr.addAll(1, 2, 3);
      assertEquals(3, arr.poll);
      assertEquals(2, arr.poll);
      assertEquals(1, arr.poll);
      assertEquals(0, arr.size);
   End;

   Macro test_indexOf()
      assertEquals(-1, arr.indexof(1));
      arr.push(null);
      assertEquals(0, arr.indexof());
      arr.push(null);
      assertEquals(0, arr.indexof());
      arr.addAll(1, 2, 1, 4);
      assertEquals(2, arr.indexof(1));
      assertEquals(3, arr.indexof(2));
   End;

   Macro test_lastindexOf()
      assertEquals(-1, arr.lastIndexof(1));
      arr.push(null);
      assertEquals(0, arr.lastIndexof(null));
      arr.push(null);
      assertEquals(1, arr.lastIndexof());
      arr.addAll(1, 2, 1, 4);
      assertEquals(4, arr.lastIndexof(1));
      assertEquals(3, arr.lastIndexof(2));
   End;

   Macro test_slice()
      assertEquals(0, arr.slice().size);
      arr.addAll(1, 2, 3);
      assertArrays(arr_(1, 2, 3), arr.slice);
      assertArrays(arr_(1, 2), arr.slice(0, 2));
      assertArrays(arr_(2, 3), arr.slice(1));

   End;

   Macro test_reverse()
      assertEquals(0, arr.reverse().size);
      arr.addAll(1, 2, 3);
      assertArrays(arr_(3, 2, 1), arr.reverse);
      assertArrays(arr_(1, 2, 3), arr.reverse);
      arr.add(4);
      assertArrays(arr_(4, 3, 2, 1), arr.reverse);
   End;

   Macro test_distinct()
      arr.addAll(1, 2, -1, 2, 3, -4, 4, 3, 0);
      assertArrays(arr_(1, 2, -1, 3, -4, 4, 0), arr.distinct);
      assertArrays(arr_(1, 2, 3, -4, 0), arr.distinct(@equalAbs));
      var a = arr.distinctSort;
      assertArrays(arr_(-4, -1, 0, 1, 2, 3, 4), arr.distinctSort());
   End;


   Macro test_clear()
      arr.addAll(1, 2, 3);
      assertEquals(3, arr.size);
      arr.clear();
      assertEquals(0, arr.size);
   End;

   Macro test_concat()
      arr.addAll(1, 2, 3);
      var arr2 = SArray(4, 5, 6, 7);
      var arrc = arr.concat(arr2);
      assertArrays(arr_(1, 2, 3, 4, 5, 6, 7), arrc);
      assertArrays(arr_(1, 2, 3), arr);
      assertArrays(arr_(4, 5, 6, 7), arr2);
      arr.clear();
      arrc = arr.concat(arr2);
      assertArrays(arr_(4,5,6,7), arrc);
      arrc = arr2.concat(arr);
      assertArrays(arr_(4,5,6,7), arrc);
      arr2.clear();
      arrc = arr2.concat(arr2);
      assertEquals(0, arrc.size);
   End;

   Macro test_addArray()
      assertArrays(arr_(1,2,3), arr.addArray(SArray(1,2,3)));
      assertEquals(3, arr.size);
      assertArrays(arr_(1,2,3,1), arr.addArray(SArray(1)));
      assertEquals(4, arr.size);
      assertArrays(arr_(1,2,3,1), arr.addArray(SArray()));
   End;

   Macro test_join()
      var s;
      s = arr.join();
      assertEquals("", s);
      s = arr.join(",", "[", "]");
      assertEquals("[]", s);

      arr.addAll(1, 2, 3);
      s = arr.join();
      assertEquals("123", s);
      s = arr.join(", ");
      assertEquals("1, 2, 3", s);
      s = arr.join(", ", "!", "?");
      assertEquals("!1, 2, 3?", s);
   End;

   Macro test_filter()

   End;

   Macro test_map()

   End;

   Macro test_reduce()

   End;

   Macro test_foreach()

   End;

   Macro test_sort()

   End;

   Macro test_iterator()

   End;

   Macro test_toTarray()

   End;


End;

/*
Class (UnitTest) TestArrayUtil()
   var arr;

   Macro beforeTest()
      arr = Arrays.of("first", 2, null, Account("4081700000000123", 100), 3, 12, Account("4081700000000666", 505), null, 2);
   End;

   Macro afterTest()

   End;

   Macro test_of()
      arr = Arrays.of("first", 2, null);
      assertEquals("first", arr[0]);
      assertEquals(2, arr[1]);
      assertNull(arr[2]);
      arr = Arrays.of();
      assertEquals(1, arr.size);
   End;

   Macro test_indexOf()
      var ind = Arrays.indexOf(arr, null);
      assertEquals(2, ind);
      ind = Arrays.indexOf(arr, 2);
      assertEquals(1, ind);
      ind = Arrays.indexOf(arr, Account("4081700000000123", 100));
      assertEquals(-1, ind);
      ind = Arrays.IndexOf(arr, Account("4081700000000123", 100), @compareJustAcc);
      assertEquals(3, ind);
      ind = Arrays.IndexOf(arr, Account("4081700000000123", 200), "compareJustAcc");
      assertEquals(3, ind);
   End;

   Macro test_lastIndexOf()
      var ind = Arrays.lastIndexOf(arr, null);
      assertEquals(7, ind);
      ind = Arrays.lastIndexOf(arr, 2);
      assertEquals(8, ind);
      ind = Arrays.lastIndexOf(arr, 4);
      assertEquals(-1, ind);

      ind = Arrays.lastIndexOf(arr, Account("4081700000000123", 100), @compareJustAcc);
      assertEquals(3, ind);
      ind = Arrays.lastIndexOf(arr, Account("4081700000000123", 200), "compareJustAcc");
      assertEquals(3, ind);
   End;

   Macro test_contains()
      assertTrue(Arrays.contains(arr, null));
      assertTrue(Arrays.contains(arr, 3));
      assertFalse(Arrays.contains(arr, 444));
      assertFalse(Arrays.contains(arr, Account("4081700000000123", 200)));
      AssertTrue(Arrays.containsNull(arr));
   End;

   Macro test_remove()
      var el = Arrays.remove(arr, 1);
      assertEquals(2, el);
      assertEquals(8, arr.size);
   End;

   Macro test_reverse()
      arr = Arrays.of(1,2,3);
      Arrays.reverse(arr);
      AssertArrays(arr_(3,2,1), arr);
   End;

   Macro test_subArray()
      arr = Arrays.of(1,2,3,4,5,6);
      var arrs = Arrays.subArray(arr, 2, 4);
      AssertArrays(arr_(3,4), arrs);
      arrs = Arrays.subArray(arr, 1);
      AssertArrays(arr_(2,3,4,5,6), arrs);
      arrs = Arrays.subArray(arr);
      AssertArrays(arr_(1,2,3,4,5,6), arrs);
   End;

   Macro test_margeArray()
      var arr1 = Arrays.of(1,2,3,4);
      var arr2 = Arrays.of(5,6,7);
      var resArr = Arrays.mergeArrays(arr1,arr2);
      assertEquals(7, resArr.size);
      assertArrays(arr_(1,2,3,4,5,6,7), resArr);
   End;

   Macro test_addArray()
      var arr1 = Arrays.of(1,2,3,4);
      var arr2 = Arrays.of(5,6,7);

      Arrays.addArray(arr1, arr2);
      assertArrays(arr_(1,2,3,4,5,6,7), arr1);
   End;


   Macro test_filter()
      var filtArr = Arrays.filter(arr, @filterFunc);
      assertArrays(arr_(2,3,12,2), filtArr);
   End;

   Macro test_map()
      arr = Arrays.of(1,2,3,4);
      var mapArr = Arrays.map(arr, @mapFunc);
      assertArrays(arr_(1,4,9,16), mapArr);
   End;

   Macro test_reduce()
      arr = Arrays.of(1,2,3,4);
      var red = Arrays.reduce(arr, @reduceFunc, 0);
      assertEquals(10, red);
   End;

   Macro test_iterator()
      arr = Arrays.of(1,2,3);
      var itr = Arrays.newIterator(arr);
      assertTrue(itr.hasNext);
      assertFalse(itr.hasPrev);
      var el = itr.next();
      AssertEquals(1, el);
      assertTrue(itr.hasPrev);
      el = itr.prev();
      AssertEquals(1, el);
      assertFalse(itr.hasPrev);
      el = itr.next();
      AssertEquals(1, el);
      el = itr.next();
      AssertEquals(2, el);
      el = itr.next();
      AssertEquals(3, el);
      AssertFalse(itr.hasNext);
      el = itr.next();
      AssertNull(el);
      AssertEquals(4, arr.size);
   End;

   Macro test_iterator_add_set_remove()
      arr = Arrays.of(1,2,3);
      var itr = Arrays.newIterator(arr);
      itr.next();
      itr.set(111);
      AssertArrays(arr_(111,2,3), arr);
      debugbreak;
      itr.add(222);
      AssertArrays(arr_(111,222,2,3), arr);
      var el = itr.next();
      AssertEquals(222, el);
   End;

End;


TestArrayUtil();
*/
debugbreak;
var arr = TArray(10, 20);
TestSArray();